// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/tokenharvest-hero/Current.tsx": () => import("../components/mockups/tokenharvest-hero/Current.tsx"),
  "./components/mockups/tokenharvest-hero/NewAge.tsx": () => import("../components/mockups/tokenharvest-hero/NewAge.tsx"),
  "./components/mockups/templates/WarmLanguageLearningDashboard-ecO4S7/App.tsx": () => import("../components/mockups/templates/WarmLanguageLearningDashboard-ecO4S7/App.tsx")
};
